#!/usr/bin/env node
/*
 * build:edge — regenerate the deployable Supabase Edge Function bundle.
 *
 *   server/edge-entry.mjs  ─┐
 *   server/*.mjs, src/lib/ ─┼─ esbuild ─> supabase/functions/sar2-api/index.ts
 *   knowledge/*.md         ─┘
 *
 * One self-contained file: the shared server code and the knowledge text are
 * inlined; only `npm:pg@8` stays an import, resolved by Deno at deploy time.
 * The output is committed so a deploy is reproducible, and the test suite
 * fails if it is out of date with the sources (test/edge-api.test.mjs).
 *
 * Usage: npm run build:edge
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const EDGE_ENTRY = join(ROOT, 'server', 'edge-entry.mjs');
export const EDGE_OUTPUT = join(ROOT, 'supabase', 'functions', 'sar2-api', 'index.ts');
export const FORECAST_KNOWLEDGE_FILE = join(ROOT, 'knowledge', 'forecasting.md');
export const KNOWLEDGE_FILE = join(ROOT, 'knowledge', 'bingo-knowledge.md');

const BANNER = [
  '// @ts-nocheck',
  '// GENERATED by `npm run build:edge` from server/edge-entry.mjs. Do not edit by hand:',
  '// change the sources (server/, src/lib/, knowledge/) and rebuild.',
  '// Supabase Edge Function `sar2-api` (Operations project lkcfbgnuodqzvowschjn).',
].join('\n');

/** Line endings are normalised so a Windows checkout builds the same bytes. */
const lf = (text) => text.replace(/\r\n?/g, '\n');

/** The bundle text, built in memory. */
export async function buildEdgeBundle() {
  const knowledgePlugin = {
    name: 'sar2-knowledge',
    setup(b) {
      b.onResolve({ filter: /^sar2:knowledge$/ }, () => ({ path: 'knowledge', namespace: 'sar2' }));
      b.onLoad({ filter: /.*/, namespace: 'sar2' }, () => ({
        contents: `export default ${JSON.stringify({ general: lf(readFileSync(KNOWLEDGE_FILE, 'utf8')), forecasting: lf(readFileSync(FORECAST_KNOWLEDGE_FILE, 'utf8')) })};`,
        loader: 'js',
      }));
    },
  };
  const result = await build({
    absWorkingDir: ROOT,
    entryPoints: [EDGE_ENTRY],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    external: ['npm:*'],
    plugins: [knowledgePlugin],
    banner: { js: BANNER },
    legalComments: 'none',
    charset: 'utf8',
    logLevel: 'silent',
  });
  return lf(result.outputFiles[0].text);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = await buildEdgeBundle();
  mkdirSync(dirname(EDGE_OUTPUT), { recursive: true });
  writeFileSync(EDGE_OUTPUT, text);
  console.log(`build:edge wrote ${EDGE_OUTPUT.slice(ROOT.length)} (${text.length} bytes)`);
}
